### PR TITLE
Rolling file by date writes to original file

### PR DESCRIPTION
**Pull request by jonsyu1**
This adds a .seelog_rolling_tracker to track the timestamp of the last log roll.

---
This change is [Reviewable](https://reviewable.io/reviews/cihub/seelog/117)

### CODE REVIEW

**Comment by jonsyu1** [comment]
Since this change removes the case of the current file being named differently from the original file, we can simplify some of the logic. I haven't done so in case there are other unimplemented cases we want to support that need to handle this case. If you don't think there are, I'll go ahead and do this cleanup.

**Comment by jonsyu1** [comment]
Testing against my own go project, and it looks like I broke sorted log history, digging into this now.

**Comment by goodsign** [comment]
Hey jonsyu1

Please check our [original discussion](https://github.com/cihub/seelog/issues/109): basically we can work with your original idea of just using `stat` because the `rollingIntervalDaily` is just a deprecated feature.

**Comment by goodsign** [comment]
I see that you already made the filename checking cleanup, so basically we could just modify this pull request to remove the `.tracker` file. Or you can create another one with your changes and with cleanup, but without the `.tracker` part, whatever is more convenient for you.

And, anyway, thanks for your contributions, that's appreciated.

**Comment by jonsyu1** [comment]
Great, I'll go ahead and modify the pull request. Thanks for taking a look. I'm excited to make use of this feature in my project's next release in the coming week!

**Comment by jonsyu1** [comment]
Hey @goodsign, just checking in to let you know that I have updated the pull request per our discussion. No rush to get it reviewed: we're using my fork in the meantime and are happy to move over once this merges :)

**Comment by goodsign** [comment]
Hey @jonsyu1 

I've tried and merged it, sorry it took a while :) Everything seems working well, so thank you for your contribution!

**Pull request merged**
