### PR TITLE
Avoid buffering logs in memory

### PR DESCRIPTION
**Pull request by jonsyu1**
**Bottom line up front**:
Instead of buffering all logs into memory before writing them to the archive,
stream directly from source to destination when the archive/compression format
matches. Otherwise, we stream to a temporary file on disk in order to compute
headers and then stream to the destination.

The high level idea is to introduce generic `archive.Reader` and
`archive.Writer` interfaces for reading files and headers from and writing files
and headers to arbitrary archive formats.

The PR is organized into the following packages. I'm happy to squash them back
into the seelog package if you want to maintain the mono-package organization.

- archive
- archive/gzip
- archive/tar
- archive/zip
- seelog

The archive package contains interfaces and static functions for working with
different archive formats. The main takeaway is the Copy function, which does
the heavy lifting for streaming logs from the source archive format to the
destination archive format. Note that Copy relies on unexported interfaces to
optimize this where the archive formats match up (inspired by io.Copy).

The subpackages underneath archive expose wrappers around the standard library's
Readers and Writers that implement the exported interfaces in the archive
package. This allows us to stream from an arbitrary `archive.Reader` to an
`archive.Writer` without worrying about header translation.

Finally, I replaced the static helper functions in `internals_fsutils.go` with
the readers and writers above. I tried to do so with minimal changes to the
rolling filewriter's architecture. `archive` and `unarchive` have been modified
to receive an open file and return the appropriate `archive.WriteCloser` or
`archive.ReadCloser` instaed of taking in or returning a map from filename to
file contents.

Additional changes I'm happy to revert:
- I also included @tstearn's fix since this also cleans up internals_fsutils.go (#125)
- I standardized on `path/filepath` since rolling filewriters depended on both
  `path` and `path/filepath` for paths on the filesystem, gaining compatability
  with non-`/`-separated filesystems.

Things I noticed (on cihub/master) while debugging:
- https://github.com/cihub/seelog/issues/130
- ~~Archiving large files causes seelog to spam `bad file descriptor`, which seems to indicate that the filewriter's `currentFile` is unavailable. This clears up after it finishes processing the large file (seconds for a 1GB file).~~ (this was because file rolling happened during archiving, which should never happen in practice)
- https://github.com/cihub/seelog/issues/131

I realize this is a rather large PR @goodsign so let me know what I can do to make this easier for you. Happy to break it out into separate commits, but I wanted to start with the full picture so you can see why I chose to approach it this way.

### CODE REVIEW

**Comment by goodsign** [comment]
Hello @jonsyu1 

First of all, thanks for the great job, that's a major contribution. 

- I like the package organization, doesn't make a lot of sense to make it flat mono-package
- fsutils fix is actually totally fine and should be included
- path/filepath standardization is fine too

Now, about those problems: if those issues happen, maybe separate issues should be created for them. I haven't tested this functionality for a while as I haven't done any go development for quite some time now, so maybe something became broken.

The PR looks fine, but it's pretty large, so give me some time to check it out.

**Comment by goodsign** [comment]
I quickly looked at the code and I like it. We need some time next weeks to look at each file and everything in more detail, but we'll probably merge it soon.

**Comment by jonsyu1** [comment]
Sounds good, thanks for your time.

I'll go ahead and file those issues.

**Comment by goodsign** [comment]
Hey @jonsyu1 
Looks like everything is ok, thank you for your contribution!

**Pull request merged**
